import json
import re

from app.providers.llm.base import LLMProvider


class MockLLMProvider(LLMProvider):
    """Deterministic, zero-cost stand-in so the full story pipeline is testable
    without an API key or a local model. Recognizes the pipeline stage from the
    prompt and returns structurally valid output for that stage.
    """

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        # "Known characters:" / "Known locations:" / etc. live in the system prompt in the
        # real prompts (see pipeline/prompts.py), so search both, combined, for stage cues.
        combined = f"{system_prompt}\n{user_prompt}"
        if "shot_number" in combined or "shots" in system_prompt.lower():
            return self._mock_shots(combined)
        if "scene_number" in combined or "scenes" in system_prompt.lower():
            return self._mock_scenes(combined)
        if "screenplay" in system_prompt.lower() or "script" in system_prompt.lower():
            return self._mock_script(user_prompt)
        return self._mock_outline(user_prompt)

    def _mock_outline(self, user_prompt: str) -> str:
        return (
            "MOCK OUTLINE (generated by MockLLMProvider - no real model was called)\n\n"
            "Act 1: The characters encounter the episode's central problem.\n"
            "Act 2: Complications escalate as they attempt to solve it.\n"
            "Act 3: Resolution, with a small twist tying back to the treatment.\n\n"
            f"Based on treatment: {_truncate(user_prompt)}"
        )

    def _mock_script(self, user_prompt: str) -> str:
        return (
            "MOCK SCRIPT (generated by MockLLMProvider - no real model was called)\n\n"
            "INT. LOCATION - DAY\n\n"
            "CHARACTER ONE\nThis is a placeholder line of dialogue.\n\n"
            "CHARACTER TWO\nAnd this is the reply.\n\n"
            f"Based on outline: {_truncate(user_prompt)}"
        )

    def _mock_scenes(self, combined_prompt: str) -> str:
        names = _extract_known_names(combined_prompt, "Known characters")
        character = names[0] if names else "Character One"
        return json.dumps(
            {
                "scenes": [
                    {
                        "scene_number": 1,
                        "location_name": _extract_known_names(combined_prompt, "Known locations", default="Unknown Location"),
                        "time_of_day": "DAY",
                        "characters_present": [character],
                        "action_description": "Mock scene 1 action, generated without a real model.",
                        "dialogue": "Placeholder dialogue for scene 1.",
                        "narration": None,
                        "emotional_tone": "neutral",
                        "estimated_duration_seconds": 30,
                    },
                    {
                        "scene_number": 2,
                        "location_name": _extract_known_names(combined_prompt, "Known locations", default="Unknown Location"),
                        "time_of_day": "DAY",
                        "characters_present": names[:2] if names else [character],
                        "action_description": "Mock scene 2 action, generated without a real model.",
                        "dialogue": "Placeholder dialogue for scene 2.",
                        "narration": None,
                        "emotional_tone": "tense",
                        "estimated_duration_seconds": 45,
                    },
                ]
            }
        )

    def _mock_shots(self, combined_prompt: str) -> str:
        names = _extract_known_names(combined_prompt, "Characters in this scene")
        character = names[0] if names else "Character One"
        return json.dumps(
            {
                "shots": [
                    {
                        "shot_number": 1,
                        "shot_type": "ESTABLISHING",
                        "camera_angle": "eye level",
                        "camera_movement": "static",
                        "characters_visible": [],
                        "action": "Mock establishing shot of the location.",
                        "dialogue": None,
                        "narration": None,
                        "emotion": None,
                        "lighting": "natural",
                        "duration_seconds": 3,
                    },
                    {
                        "shot_number": 2,
                        "shot_type": "MEDIUM",
                        "camera_angle": "eye level",
                        "camera_movement": "static",
                        "characters_visible": [character],
                        "action": "Mock medium shot on the character speaking.",
                        "dialogue": "Placeholder shot dialogue.",
                        "narration": None,
                        "emotion": "neutral",
                        "lighting": "natural",
                        "duration_seconds": 4,
                    },
                ]
            }
        )


def _truncate(text: str, length: int = 80) -> str:
    text = text.strip().replace("\n", " ")
    return text[:length] + ("..." if len(text) > length else "")


def _extract_known_names(user_prompt: str, label: str, default: str | None = None) -> list[str] | str:
    match = re.search(rf"{re.escape(label)}:\s*(.+)", user_prompt)
    if not match:
        return [] if default is None else default
    names = [n.strip() for n in match.group(1).split(",") if n.strip()]
    if default is not None:
        return names[0] if names else default
    return names
