"""automated QC: qc_notes on generations

Revision ID: 3aa50c25e627
Revises: d057d6762e9e
Create Date: 2026-08-08 03:02:29.495261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa50c25e627'
down_revision: Union[str, None] = 'd057d6762e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('qc_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'qc_notes')
    # ### end Alembic commands ###
