"""initial schema

Revision ID: 41f324352718
Revises: 
Create Date: 2026-08-08 00:36:24.951316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f324352718'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_settings_key'), 'project_settings', ['key'], unique=True)
    op.create_table('provider_configurations',
    sa.Column('capability', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_configurations_capability'), 'provider_configurations', ['capability'], unique=False)
    op.create_table('series',
    sa.Column('series_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('animation_style', sa.String(length=200), nullable=True),
    sa.Column('target_resolution', sa.String(length=20), nullable=False),
    sa.Column('default_fps', sa.Integer(), nullable=False),
    sa.Column('target_episode_length_minutes', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('visual_style_prompt', sa.Text(), nullable=True),
    sa.Column('negative_style_prompt', sa.Text(), nullable=True),
    sa.Column('default_voice_settings', sa.Text(), nullable=True),
    sa.Column('default_video_provider', sa.String(length=100), nullable=True),
    sa.Column('default_image_provider', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_series_code'), 'series', ['series_code'], unique=True)
    op.create_table('characters',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('character_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('age_range', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('build', sa.String(length=100), nullable=True),
    sa.Column('skin_tone', sa.String(length=100), nullable=True),
    sa.Column('hair', sa.String(length=200), nullable=True),
    sa.Column('facial_features', sa.Text(), nullable=True),
    sa.Column('clothing', sa.Text(), nullable=True),
    sa.Column('accessories', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('movement_style', sa.Text(), nullable=True),
    sa.Column('speaking_style', sa.Text(), nullable=True),
    sa.Column('accent', sa.String(length=100), nullable=True),
    sa.Column('visual_style_notes', sa.Text(), nullable=True),
    sa.Column('continuity_restrictions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_character_code'), 'characters', ['character_code'], unique=True)
    op.create_index(op.f('ix_characters_series_id'), 'characters', ['series_id'], unique=False)
    op.create_table('episodes',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('episode_code', sa.String(length=32), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('target_runtime_seconds', sa.Integer(), nullable=True),
    sa.Column('current_estimated_runtime_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCRIPT_READY', 'SCENES_READY', 'STORYBOARD_READY', 'RENDERING', 'QC', 'COMPLETE', name='episodestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'episode_number', name='uq_episode_series_number')
    )
    op.create_index(op.f('ix_episodes_episode_code'), 'episodes', ['episode_code'], unique=False)
    op.create_index(op.f('ix_episodes_series_id'), 'episodes', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_series_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_episode_code'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_characters_series_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_character_code'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_series_series_code'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_provider_configurations_capability'), table_name='provider_configurations')
    op.drop_table('provider_configurations')
    op.drop_index(op.f('ix_project_settings_key'), table_name='project_settings')
    op.drop_table('project_settings')
    # ### end Alembic commands ###
