"""character bible: references, outfits, voices, locations, props

Revision ID: daf1e3f61d87
Revises: 41f324352718
Create Date: 2026-08-08 01:05:40.394499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf1e3f61d87'
down_revision: Union[str, None] = '41f324352718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lighting_notes', sa.Text(), nullable=True),
    sa.Column('time_of_day_notes', sa.Text(), nullable=True),
    sa.Column('camera_reference_notes', sa.Text(), nullable=True),
    sa.Column('important_props', sa.Text(), nullable=True),
    sa.Column('continuity_rules', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_location_code'), 'locations', ['location_code'], unique=True)
    op.create_index(op.f('ix_locations_series_id'), 'locations', ['series_id'], unique=False)
    op.create_table('props',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('prop_code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_props_prop_code'), 'props', ['prop_code'], unique=True)
    op.create_index(op.f('ix_props_series_id'), 'props', ['series_id'], unique=False)
    op.create_table('character_outfits',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('outfit_code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_outfits_character_id'), 'character_outfits', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_outfits_outfit_code'), 'character_outfits', ['outfit_code'], unique=True)
    op.create_table('character_references',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('FRONT', 'SIDE', 'THREE_QUARTER', 'FULL_BODY', 'CLOSE_UP', 'HAPPY', 'ANGRY', 'SAD', 'TALKING', 'SITTING', 'WALKING', 'RUNNING', 'ADDITIONAL', name='characterreferencecategory'), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_references_category'), 'character_references', ['category'], unique=False)
    op.create_index(op.f('ix_character_references_character_id'), 'character_references', ['character_id'], unique=False)
    op.create_table('location_references',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('WIDE_ESTABLISHING', 'MEDIUM', 'CLOSE_BACKGROUND', 'INTERIOR_NORTH', 'INTERIOR_SOUTH', 'INTERIOR_EAST', 'INTERIOR_WEST', 'ADDITIONAL', name='locationreferencecategory'), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_references_category'), 'location_references', ['category'], unique=False)
    op.create_index(op.f('ix_location_references_location_id'), 'location_references', ['location_id'], unique=False)
    op.create_table('prop_references',
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prop_id'], ['props.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_references_prop_id'), 'prop_references', ['prop_id'], unique=False)
    op.create_table('voices',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('voice_code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_voice_id', sa.String(length=200), nullable=True),
    sa.Column('reference_audio_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('speaking_style', sa.Text(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('emotion', sa.String(length=100), nullable=True),
    sa.Column('generation_settings', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voices_character_id'), 'voices', ['character_id'], unique=False)
    op.create_index(op.f('ix_voices_series_id'), 'voices', ['series_id'], unique=False)
    op.create_index(op.f('ix_voices_voice_code'), 'voices', ['voice_code'], unique=True)
    op.create_table('outfit_references',
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['character_outfits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_references_outfit_id'), 'outfit_references', ['outfit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_references_outfit_id'), table_name='outfit_references')
    op.drop_table('outfit_references')
    op.drop_index(op.f('ix_voices_voice_code'), table_name='voices')
    op.drop_index(op.f('ix_voices_series_id'), table_name='voices')
    op.drop_index(op.f('ix_voices_character_id'), table_name='voices')
    op.drop_table('voices')
    op.drop_index(op.f('ix_prop_references_prop_id'), table_name='prop_references')
    op.drop_table('prop_references')
    op.drop_index(op.f('ix_location_references_location_id'), table_name='location_references')
    op.drop_index(op.f('ix_location_references_category'), table_name='location_references')
    op.drop_table('location_references')
    op.drop_index(op.f('ix_character_references_character_id'), table_name='character_references')
    op.drop_index(op.f('ix_character_references_category'), table_name='character_references')
    op.drop_table('character_references')
    op.drop_index(op.f('ix_character_outfits_outfit_code'), table_name='character_outfits')
    op.drop_index(op.f('ix_character_outfits_character_id'), table_name='character_outfits')
    op.drop_table('character_outfits')
    op.drop_index(op.f('ix_props_series_id'), table_name='props')
    op.drop_index(op.f('ix_props_prop_code'), table_name='props')
    op.drop_table('props')
    op.drop_index(op.f('ix_locations_series_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_code'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
