"""storyboard generation: Generation entity

Revision ID: e8286dcd42dc
Revises: eecb9808438d
Create Date: 2026-08-08 01:54:18.415241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8286dcd42dc'
down_revision: Union[str, None] = 'eecb9808438d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('generation_type', sa.Enum('IMAGE', 'VIDEO', name='generationtype'), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('workflow_version', sa.String(length=100), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('generation_settings', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PREPARING', 'RUNNING', 'PROCESSING', 'COMPLETE', 'FAILED', 'CANCELED', name='generationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_path', sa.String(length=500), nullable=True),
    sa.Column('preview_path', sa.String(length=500), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_generation_type'), 'generations', ['generation_type'], unique=False)
    op.create_index(op.f('ix_generations_shot_id'), 'generations', ['shot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_shot_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_generation_type'), table_name='generations')
    op.drop_table('generations')
    # ### end Alembic commands ###
