"""story pipeline: episode outline, series bible fields, scenes, shots

Revision ID: eecb9808438d
Revises: daf1e3f61d87
Create Date: 2026-08-08 01:31:22.350550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecb9808438d'
down_revision: Union[str, None] = 'daf1e3f61d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.Text(), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('dialogue', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('emotional_tone', sa.Text(), nullable=True),
    sa.Column('continuity_notes', sa.Text(), nullable=True),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SHOTS_READY', name='scenestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'scene_number', name='uq_scene_episode_number')
    )
    op.create_index(op.f('ix_scenes_episode_id'), 'scenes', ['episode_id'], unique=False)
    op.create_index(op.f('ix_scenes_location_id'), 'scenes', ['location_id'], unique=False)
    op.create_table('scene_characters',
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['character_outfits.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'character_id', name='uq_scene_character')
    )
    op.create_index(op.f('ix_scene_characters_character_id'), 'scene_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_scene_characters_scene_id'), 'scene_characters', ['scene_id'], unique=False)
    op.create_table('shots',
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.Enum('ESTABLISHING', 'EXTREME_WIDE', 'WIDE', 'MEDIUM', 'MEDIUM_CLOSE_UP', 'CLOSE_UP', 'EXTREME_CLOSE_UP', 'OVER_THE_SHOULDER', 'TWO_SHOT', 'REACTION_SHOT', 'INSERT_SHOT', 'POV', 'TRACKING', 'PAN', 'TILT', 'STATIC', name='shottype'), nullable=False),
    sa.Column('camera_angle', sa.Text(), nullable=True),
    sa.Column('camera_movement', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('dialogue', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('emotion', sa.Text(), nullable=True),
    sa.Column('lighting', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'shot_number', name='uq_shot_scene_number')
    )
    op.create_index(op.f('ix_shots_scene_id'), 'shots', ['scene_id'], unique=False)
    op.create_table('shot_characters',
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['character_outfits.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'character_id', name='uq_shot_character')
    )
    op.create_index(op.f('ix_shot_characters_character_id'), 'shot_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_shot_characters_shot_id'), 'shot_characters', ['shot_id'], unique=False)
    op.add_column('episodes', sa.Column('outline', sa.Text(), nullable=True))
    op.add_column('series', sa.Column('world_details', sa.Text(), nullable=True))
    op.add_column('series', sa.Column('continuity_rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'continuity_rules')
    op.drop_column('series', 'world_details')
    op.drop_column('episodes', 'outline')
    op.drop_index(op.f('ix_shot_characters_shot_id'), table_name='shot_characters')
    op.drop_index(op.f('ix_shot_characters_character_id'), table_name='shot_characters')
    op.drop_table('shot_characters')
    op.drop_index(op.f('ix_shots_scene_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_scene_characters_scene_id'), table_name='scene_characters')
    op.drop_index(op.f('ix_scene_characters_character_id'), table_name='scene_characters')
    op.drop_table('scene_characters')
    op.drop_index(op.f('ix_scenes_location_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_episode_id'), table_name='scenes')
    op.drop_table('scenes')
    # ### end Alembic commands ###
