"""episode assembler: EpisodeExport

Revision ID: fef4d421a572
Revises: 3aa50c25e627
Create Date: 2026-08-08 03:24:51.877092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef4d421a572'
down_revision: Union[str, None] = '3aa50c25e627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_exports',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PREPARING', 'RUNNING', 'PROCESSING', 'COMPLETE', 'FAILED', 'CANCELED', name='generationstatus'), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('include_titles', sa.Boolean(), nullable=False),
    sa.Column('include_credits', sa.Boolean(), nullable=False),
    sa.Column('include_subtitles', sa.Boolean(), nullable=False),
    sa.Column('skipped_shots', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_exports_episode_id'), 'episode_exports', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_exports_episode_id'), table_name='episode_exports')
    op.drop_table('episode_exports')
    # ### end Alembic commands ###
